name: "Deploy to WordPress.org"

on: 
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          composer install --no-dev --no-interaction --no-progress --optimize-autoloader
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        id: deploy
        with:
          dry-run: true
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: fewer-tags # optional, remove if GitHub repo name matches SVN slug, including capitalization
